config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'welcome/index'

  resources :teams

  resources :projects


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  Roles = [ "User", "Admin" , "DevOps" ]

  def initialize(current_user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if current_user.present? && current_user.position == 'Admin'
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	# belongs_to :team
	has_and_belongs_to_many :users

	# validates :name, :presence => true, :on => :save

    # validates_presence_of :title, message: "can't be blank"
    validates_presence_of :title, :name, :team_id, :description, message: "can't be blank"
end

app/models/team.rb
class Team < ApplicationRecord
   has_many :users
   has_many :projects

   validates_presence_of :name, message: "can't be blank"
   validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_and_belongs_to_many :projects
   has_many :teams

   validates :name, :presence => true, :on => :save
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :position, :team_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if current_user.position == 'Admin'
     @projects = Project.all
    else
     @projects = current_user.projects
    end
     @users= User.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    @teams = Team.all
    @users = User.all
    # @current_user = current_user
  end

  # GET /projects/1/edit
  def edit
    @teams = Team.all
    @users = User.all
  end


  # POST /projects
  # POST /projects.json
  def create

    @teams = Team.all
    @users = User.all
    @project = current_user.projects.build(project_params)
    @teams = Team.all

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @teams = Team.all
    @users = User.all
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      #params.fetch(:project, {})
      params.require(:project).permit(:title, :name, :description, :team_id, :status, user_ids:[])
      #params.require(:project).permit(:title, :name, :description, :team_id, :user_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      #params.fetch(:team, {})

      params.require(:team).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@projects = Project.all
  	@users = User.all
  	@teams = Team.all
  	@npc =Project.all.where(status: 'New').count
  	@ipc =Project.all.where(status: 'In progress').count
  	@dpc =Project.all.where(status: 'Done').count
  	@sgp=User.joins(:projects).group(:status).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manaproj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:powderblue;" >
    <div class="container">
      <%= link_to root_path, class:"navbar-item" do %>
       <h1><i>ManaProj</i></h1>
      <% end  %>
      <div align="right">
		    <% if user_signed_in? %>
  			 Logged in as <strong><%= current_user.name %></strong>.
  			 <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			 <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>  			       
		    <% else %>
  			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
 			    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		    <% end %>
      </div>
	  </div>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      <div class="field">
        <div class="control">
          <%= form.label :title %>
          <%= form.text_field :title %>
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= form.label :description %>
          <%= form.text_area :description%>
        </div>
        <div class="select">
          <%= form.select :team_id, options_for_select(@teams.collect{ |u| [u.name, u.id] }), {:prompt => 'Select Team'}  %>
        </div>
         <div class="field">
          <%= form.label "Assign Developers" %>
          <select data-placeholder="click and add Developers" multiple="multiple" class="chosen-select" 
            name="project[user_ids][]">    
           <% @users.collect do |u| %> 
           <% if u.position == 'DevOps' %>
             <option value=<%= u.id %> > 
                <%= u.name %> 
             </option> 
           <%end%>             
           <% end %>
          </select>
          <div>
            <select name="project[status]">
             <option value="New">New</option>
             <option value="In Progress">In Progress</option>
             <option value="Done">Done</option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <% if can? :manage, Project %>
    <%= form.submit %>
    <% end%>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script>
  <link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet"/>
  <script type="text/javascript">$(".chosen-select").chosen({  no_results_text: "Oops, nothing found!"})</script>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>
<div align="right" ><%= link_to 'New Project', new_project_path if can? :manage, Project %></div>

<table style="width:100%" border="1">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Name</th>
      <th>Description</th>
      <th>Team ID</th>
      <!-- <th>Users IDs</th> -->
      <th>Developers Name</th>
      <th>Status</th>
      <th colspan="3">Take Action</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.id %></td>
        <td><%= project.title %></td>
        <td><%= project.name.upcase %></td>
        <td><%= project.description %></td>
        <td><%= project.team_id %></td>
        <!-- <td><%= project.user_ids %> </td> -->
        <td>
         <% @users.find(project.user_ids).each do |ui|%>
         <ul> <%= ui.id %>. <%= ui.name.upcase %></ul>
         <%end%>
         </td>

        <td><%= project.status %></td>
        
        <td><%= link_to 'Show', project %></td>
        <% if can? :manage, Project %>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Name</th>
      <th>Description</th>
      <th>Team ID</th>
      <th>Users IDs</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @projects.id %></td>
        <td><%= @projects.title %></td>
        <td><%= @projects.name %></td>
        <td><%= @projects.description %></td>
        <td><%= @projects.team_id %></td>
        <td><%= @projects.user_ids %> </td>
        <td><%= @projects.status %></td>
      </tr>
  </tbody>
</table>

<% if can? :manage, Project %>
 <%= link_to 'Edit', edit_project_path(@project) %>
<%end%> |
 <%= link_to 'Back', projects_path %>

app/views/welcome/_admin_welcome.html.erb
<table style="width:100%">   
  <thead>
      <tr>
        <th>Status</th>
      	  <% @users.map do |u| %> 
            <% if u.position == 'DevOps' %>
              <th><%=u.id%>.  Developer <%= u.name.upcase %> </th> 
            <%end%>
          <%end%>          
      </tr>
  </thead>
    <tbody>  
      <% @projects.group(:status).each do |p|%>
        <tr> 
         	<td><%= p.status %></td>       
            <% @users.collect do |u| %> 
            <% if u.position == 'DevOps' %> 
              <td>
                <% u.projects.each do |up| %> 
                  <% if up.user_ids.include? u.id and p.status == up.status %>                    
                      <ul> Project                   
                       <%=up.id%>. <%=up.name %>
                      </ul>              
                  <%end%>
                <%end%>
              </td>                
            <%end%>  
            <%end%>     
          </tr>
        <%end%>
    </tbody>
    <style> table, th, td {  border: 1px solid black;  border-collapse: collapse; }</style>
</table>

app/views/welcome/_developer_welcome.html.erb
<table style="width:100%">   
  <thead>
      <tr>
        <th>Status</th>
      	  <% current_user.projects.map do |ps| %> 
              <th><%=ps.id%>.  Project <%= ps.name %> </th> 
          <%end%>          
      </tr>
  </thead>
    <tbody>  
      <% @projects.group(:status).each do |p|%>
        <tr> 
         	<td><%= p.status %></td> 
            <% current_user.projects.map do |ups|%>      
             <td>
             <% if ups.user_ids.include? current_user.id and p.status == ups.status and ups.status != 'Done'%>                    
                <ul> Description :                   
                  <%=ups.description %> |
            <select name="project[status]">
             <option value="In Progress">In Progress</option>
             <option value="Done">Done</option>
            </select>
            <%= link_to 'Update', edit_project_path(p.id) %>
                </ul>  
              <%elsif ups.user_ids.include? current_user.id and p.status == ups.status and ups.status == 'Done'%>
                <ul>   
                 <%=ups.description %>
                </ul>  
              <%elsif%>
                <ul>               
                  none 
                </ul>                            
              <%end%>
            </td>
            <%end%>   
          </tr>
        <%end%>
    </tbody>
    <style> table, th, td {  border: 1px solid black;  border-collapse: collapse; }</style>
</table>

app/views/welcome/index.html.erb
<h2 align="right" id="notice"><%= notice %></h2>

	<h2>
	  <div align="right">
        <%= link_to 'Project', projects_path, :class => 'navbar-link' %>
        <%= link_to 'Team', teams_path, :class => 'navbar-link' %>
    </div>
  </h2>
<h1><%= current_user.name.upcase %> In Action as <%= current_user.position %></h1>
<% if user_signed_in? and current_user.position == 'Admin'%>
	<%= render :partial => 'admin_welcome.html.erb' %>
<% elsif current_user.position == 'DevOps'%>
  <%= render :partial => 'developer_welcome.html.erb' %>   
<% end %>

  <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and

      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Status');
        data.addColumn('number', 'Count');
        data.addRows([
          ['New', 5],
          ['In Progress', 3],
          ['Done', 1]
        ]);

        // Set chart options
        var options = {'title':'Developers In Action',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
<div id="chart_div"></div>

  